"""Add Phase 2 Simulation Models

Revision ID: b76cafb5dc4e
Revises: 
Create Date: 2026-05-10 06:57:51.194786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76cafb5dc4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('triage_level', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('medical_history', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('patients', sa.Column('medications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'medications')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'medical_history')
    op.drop_column('patients', 'triage_level')
    # ### end Alembic commands ###
